-   id: nbconvert
    name: nbconvert
    description: Generic nbconvert command
    language: system
    entry: jupyter nbconvert 
    types: [jupyter]

-   id: clear-outputs
    name: clear-outputs
    description: Clears output of jupyter notebooks.
    entry: clear-outputs
    language: python
    types: [jupyter]
    stages: [commit]