repos:
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
    -   id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
    -   id: ruff-format
        types_or: [python, pyi, jupyter]
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.0 
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
    -   id: poetry-install
