-   id: nbconvert
    name: nbconvert
    description: Generic nbconvert command
    language: system
    entry: jupyter nbconvert 
    types: [jupyter]

-   id: convert-notebooks
    name: convert-notebooks
    description: Convert non-cleared notebooks into specified format
    entry: convert
    args: [--format=html]
    language: python
    types: [jupyter]
    stages: [commit]

-   id: clear-notebook-outputs
    name: clear-notebook-outputs
    description: Clears output of jupyter notebooks
    entry: clear-outputs
    language: python
    types: [jupyter]
    stages: [commit]